### ISSUE TITLE
no prediction of the attack 

### ISSUE THREAD

**Issue by ameni1997** [ozch/SSH-Attack-Detection-Using-Machine-Learning#1]
hello, i used your code to detect a brute force attack for a very important project , but unfortunately it didn't predict the presence of the attack ,i used google colab , here is the screenshots of the whole code , i'm a very beginner in the machine learning and i spent nights to troubleshoot the problem but it was in vain , can you help me please   
![image](https://user-images.githubusercontent.com/63421974/163805202-2f235fd2-d1ac-40e5-b1ae-c708b631a7ab.png)
![image](https://user-images.githubusercontent.com/63421974/163805259-2d4e2432-a01e-46f6-914e-5107c356fe36.png)
![image](https://user-images.githubusercontent.com/63421974/163805320-06819d4a-bfd8-42fb-bb95-1fc249baca78.png)
![image](https://user-images.githubusercontent.com/63421974/163805411-c5f7e3ea-cdbb-425a-a603-dbeae39f53f4.png)
![image](https://user-images.githubusercontent.com/63421974/163805443-c05bd551-0690-4fce-9a6c-c6f23053efdd.png)
![image](https://user-images.githubusercontent.com/63421974/163805493-31927c09-c564-44c2-abe6-f631242a1195.png)
![image](https://user-images.githubusercontent.com/63421974/163805557-41ea27ab-2530-49ff-ac91-357c0996583a.png)
![image](https://user-images.githubusercontent.com/63421974/163805607-709508e8-4e68-4a04-b05e-79a7133825d3.png)
![image](https://user-images.githubusercontent.com/63421974/163805652-6c5e48e4-890b-420a-85d8-71fe10d86789.png)
![image](https://user-images.githubusercontent.com/63421974/163805808-4273115c-1002-4f46-bc85-919806d7cc59.png)
![image](https://user-images.githubusercontent.com/63421974/163805827-244bfa54-3f96-4496-ac1d-8ed522d145fa.png)
here is the result it just keep running and there is no output 
![image](https://user-images.githubusercontent.com/63421974/163806445-9a2975e9-5eca-4daa-9e00-0afe7e27c480.png)

**Comment by ozch** [comment]
[ameni1997](https://github.com/ameni1997) please refer to this snippet
https://github.com/ozch/SSH-Attack-Detection-Using-Machine-Learning/blob/02c3e02d69481b25709b73f48e08e4e24dbd9020/main_ssh.py#L9-L17

Hey, auth_path refers to the Linux sshd log file, OS will keep adding new logs(lines of information) to it as new ssh connection attempts are made, this program monitors auth.log file by tailing it (reading as new log are added). 

As new ssh connection attempts are made, program will read it from auth.log file and will try to extract all the features and predict whether if it's an attack or not

This programs needs to be run on a linux machine (i only tested it on ubuntu)
- Set up ssh server on Linux (ubuntu) machine.
- Add all the usernames to ssh_parse.py file 
- https://github.com/ozch/SSH-Attack-Detection-Using-Machine-Learning/blob/02c3e02d69481b25709b73f48e08e4e24dbd9020/ssh_parse.py#L8
- Then you can attack that machine

**Comment by ozch** [comment]
@ameni1997 I would recommend reading the methodology section from student research paper linked in README.md file to better understand the implementation.

**Comment by ozch** [comment]
Please send me complete error log and system specifications

________________________________
